# Generated by Django 6.0.1 on 2026-02-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(max_length=100)),
                ('ProductName', models.CharField(max_length=100, unique=True)),
                ('Description', models.TextField()),
                ('Price', models.FloatField()),
                ('ProductImage', models.ImageField(upload_to='products')),
            ],
        ),
    ]
