# Generated by Django 6.0.1 on 2026-03-01 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminApp", "0002_productdb"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productdb",
            name="ProductImage",
        ),
        migrations.CreateModel(
            name="ProductImageDb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="products")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="AdminApp.productdb",
                    ),
                ),
            ],
        ),
    ]
