# Generated by Django 6.0.1 on 2026-03-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminApp", "0003_remove_productdb_productimage_productimagedb"),
    ]

    operations = [
        migrations.AddField(
            model_name="productdb",
            name="ProductImage",
            field=models.ImageField(blank=True, null=True, upload_to="products"),
        ),
    ]
