# Generated by Django 6.0.1 on 2026-02-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_registrationdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='CratDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(blank=True, max_length=100, null=True)),
                ('ProductName', models.CharField(blank=True, max_length=100, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('Price', models.FloatField(blank=True, null=True)),
                ('TotalPrice', models.FloatField(blank=True, null=True)),
                ('ProductImage', models.ImageField(blank=True, null=True, upload_to='Cart Images')),
            ],
        ),
    ]
