# Generated by Django 6.0.1 on 2026-03-03 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("UserApp", "0004_orderdb"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CratDb",
            new_name="CartDb",
        ),
    ]
